//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.Threading.Tasks;

namespace HeavyClient.RoutingService {
    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/RoutingService")]
    [Serializable()]
    public partial class CompositeType : object, IExtensibleDataObject, INotifyPropertyChanged {
        
        [NonSerialized()]
        private ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private bool BoolValueField;
        
        [OptionalField()]
        private string StringValueField;
        
        [Browsable(false)]
        public ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [DataMember()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="RoutingService.IRoutingService")]
    public interface IRoutingService {
        
        [OperationContract(Action="http://tempuri.org/IRoutingService/GetData", ReplyAction="http://tempuri.org/IRoutingService/GetDataResponse")]
        string GetData(int value);
        
        [OperationContract(Action="http://tempuri.org/IRoutingService/GetData", ReplyAction="http://tempuri.org/IRoutingService/GetDataResponse")]
        Task<string> GetDataAsync(int value);
        
        [OperationContract(Action="http://tempuri.org/IRoutingService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IRoutingService/GetDataUsingDataContractResponse")]
        CompositeType GetDataUsingDataContract(CompositeType composite);
        
        [OperationContract(Action="http://tempuri.org/IRoutingService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IRoutingService/GetDataUsingDataContractResponse")]
        Task<CompositeType> GetDataUsingDataContractAsync(CompositeType composite);
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IRoutingServiceChannel : IRoutingService, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class RoutingServiceClient : ClientBase<IRoutingService>, IRoutingService {
        
        public RoutingServiceClient() {
        }
        
        public RoutingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoutingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoutingServiceClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoutingServiceClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public CompositeType GetDataUsingDataContract(CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public Task<CompositeType> GetDataUsingDataContractAsync(CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
